### ISSUE TITLE
Request to update to latest langchain 0.0.243

### ISSUE THREAD

**Issue by taposh** [nyanp/chat2plot#4]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-ai 0.7.1 requires langchain==0.0.158, but you have langchain 0.0.243 which is incompatible.

Can you update langchain to latest 0.0.243?

**Comment by nyanp** [comment]
@taposh 
It seems that it is caused by dependency of (old) jupyter-ai, not chat2plot. Update jupyter-ai in your environment may solve the issue.

> jupyter-ai 0.7.1 requires langchain==0.0.158
